language: cpp
sudo: false
dist: xenial
os:
  - linux
  - osx

env:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:
    ############################################################################
    # Builds with GCC
    ############################################################################
    - os: linux
      env: CC=gcc-7 CXX=g++-7 OTHER_ARGS="-DCMAKE_BUILD_TYPE=Debug"
      addons:
        apt:
          packages:
            - g++-7
            - ninja-build
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: CC=gcc-7 CXX=g++-7 OTHER_ARGS="-DCMAKE_BUILD_TYPE=Debug -DLBFGS_USE_BLAS=ON"
      addons:
        apt:
          packages:
            - g++-7
            - libopenblas-dev
            - ninja-build
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: CC=gcc-7 CXX=g++-7 OTHER_ARGS="-DCMAKE_BUILD_TYPE=Release -DLBFGS_DEBUG=OFF"
      addons:
        apt:
          packages:
            - g++-7
            - libopenblas-dev
            - ninja-build
          sources:
            - ubuntu-toolchain-r-test

    ############################################################################
    # Builds with GCC
    ############################################################################
    - os: linux
      env: CC=clang-5.0 CXX=clang++-5.0 OTHER_ARGS="-DCMAKE_BUILD_TYPE=Debug"
      addons:
        apt:
          packages:
            - g++-7 # For a relatively up-to-date libstdc++
            - clang-5.0
            - ninja-build
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: CC=clang-5.0 CXX=clang++-5.0 OTHER_ARGS="-DCMAKE_BUILD_TYPE=Debug -DLBFGS_USE_BLAS=ON"
      addons:
        apt:
          packages:
            - g++-7 # For a relatively up-to-date libstdc++
            - clang-5.0
            - libopenblas-dev
            - ninja-build
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: CC=clang-5.0 CXX=clang++-5.0 OTHER_ARGS="-DCMAKE_BUILD_TYPE=Release -DLBFGS_DEBUG=OFF"
      addons:
        apt:
          packages:
            - g++-7 # For a relatively up-to-date libstdc++
            - clang-5.0
            - libopenblas-dev
            - ninja-build
          sources:
            - ubuntu-toolchain-r-test

install:
  - mkdir build && cd build
  - cmake -G Ninja $OTHER_ARGS ..
  - cmake --build .

script:
  - ./test/run_tests
