language: cpp
sudo: false
dist: xenial
os:
  - linux
  - osx

env:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:
    ############################################################################
    # Builds with GCC
    ############################################################################
    - os: linux
      env: CC=gcc-7 COMPILER=g++-7
      addons:
        apt:
          packages:
            - g++-7
            - ninja-build
          sources:
            - ubuntu-toolchain-r-test

install:
  - mkdir build && cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .

script:
  - ./test/run_tests
